# Generated by Django 6.0.2 on 2026-02-07 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование объекта')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Короткий код')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('operation_type', models.CharField(choices=[('incoming', 'Приход'), ('move', 'Перемещение'), ('writeoff', 'Списание')], max_length=20, verbose_name='Тип операции')),
                ('item_name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('serial', models.CharField(blank=True, max_length=255, null=True, verbose_name='Серийный номер')),
                ('quantity', models.FloatField(default=1, verbose_name='Количество')),
                ('unit', models.CharField(default='шт', max_length=50, verbose_name='Единица измерения')),
                ('from_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Откуда')),
                ('to_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Куда')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.site', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
