# Generated by Django 6.0.2 on 2026-02-07 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='site',
        ),
        migrations.AddField(
            model_name='operation',
            name='from_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations_from', to='main.site', verbose_name='Откуда (склад)'),
        ),
        migrations.AddField(
            model_name='operation',
            name='to_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations_to', to='main.site', verbose_name='Куда (склад)'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='from_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Откуда (локация)'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='to_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Куда (локация)'),
        ),
    ]
