# Generated by Django 6.0.2 on 2026-02-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_and_invoice_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='inventory_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(choices=[('incoming', 'Приход'), ('move', 'Перемещение'), ('writeoff', 'Списание'), ('issue', 'Выдача (расход)')], max_length=20, verbose_name='Тип операции'),
        ),
    ]
