"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', '')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

_raw_hosts_ = os.environ.get('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h.strip() for h in _raw_hosts_.split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main.apps.MainConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
  "default": {
    "ENGINE": "django.db.backends.sqlite3",
    "NAME": BASE_DIR / "data" / "db.sqlite3",
  }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Asia/Yakutsk'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'

# Media (для PDF накладных и др.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Email/SMTP (через env, без хардкода)
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', '1') in ('1', 'true', 'True', 'yes', 'YES')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'no-reply@local-agent')

ACCOUNTING_EMAIL = os.environ.get('ACCOUNTING_EMAIL', '')

# === Локальный склад (где установлено ПО) ===
# Один инстанс приложения обслуживает «свой» склад.
# Все операции должны затрагивать этот склад (move не может быть между двумя «чужими» складами).
#
# Имя можно задать через env LOCAL_SITE_NAME, но приоритетнее настройка в админке
# (Настройки приложения -> LOCAL_SITE_NAME).
LOCAL_SITE_NAME = os.environ.get('LOCAL_SITE_NAME', '').strip()
LOCAL_SITE_ID = int(os.environ.get("LOCAL_SITE_ID", "1"))

# === Почта офиса (куда слать накладные) ===
# Для обратной совместимости OFFICE_EMAIL по умолчанию берётся из ACCOUNTING_EMAIL.
# Приоритетнее настраивается через админку (Настройки приложения -> Email для накладных).
OFFICE_EMAIL = os.environ.get('OFFICE_EMAIL', ACCOUNTING_EMAIL).strip()

# Реквизиты для накладной (можно переопределить env)
INVOICE_SHIPPER = os.environ.get('INVOICE_SHIPPER', 'Грузоотправитель: (укажите INVOICE_SHIPPER в env)')
INVOICE_CONSIGNEE = os.environ.get('INVOICE_CONSIGNEE', 'ООО АС «Горизонт»')
INVOICE_PERMIT_BY = os.environ.get('INVOICE_PERMIT_BY', 'Отпуск разрешил: __________________')

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'